spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estoques
    username: postgres          # ou o usuário que você criou
    password: Mcartney42!
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

server:
  port: 8080